name: LSM
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - opencv
  - pip

  - pip:
      - mediapipe==0.10.9
      - absl-py
      - attrs
      - cffi
      - flatbuffers
      - fonttools
      - kiwisolver
      - contourpy
      - cycler
      - packaging
      - pillow
      - protobuf
      - pycparser
      - pyparsing
      - python-dateutil
      - six
      - sounddevice
